name: Release NPM Package
on:
  push:
    branches: [main]
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - name: Build Project
        run: npm run build
      - run: npm run release
